package GUI;
import Objek.Shuttlecock;

/**
 *
 * @author Bima Hamdani Mawaridi
 */
public class GUI_Shuttlecock extends javax.swing.JFrame {

    Shuttlecock shuttle = new Shuttlecock();                                                        //membuat objek referensi dari class Shuttlecock
     
    public GUI_Shuttlecock() {
        initComponents();
         jT_Harga2.setEditable(false);
         jT_Total2.setEditable(false);
         jT_Ongkir2.setEditable(false);
         jTA_Cetak2.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jT_Total2 = new javax.swing.JTextField();
        jT_Jumlah2 = new javax.swing.JTextField();
        jT_Harga2 = new javax.swing.JTextField();
        jT_IDbarang2 = new javax.swing.JTextField();
        jT_Ongkir2 = new javax.swing.JTextField();
        jL_JasaKirim = new javax.swing.JLabel();
        jL_IDbarang = new javax.swing.JLabel();
        jL_Bayar = new javax.swing.JLabel();
        jL_Ongkir = new javax.swing.JLabel();
        jL_Pesan = new javax.swing.JLabel();
        jL_Total = new javax.swing.JLabel();
        jL_Harga = new javax.swing.JLabel();
        jL_Merk = new javax.swing.JLabel();
        jL_Jumlah = new javax.swing.JLabel();
        jC_Merk2 = new javax.swing.JComboBox<>();
        jC_JasaKirim2 = new javax.swing.JComboBox<>();
        jC_Pembayaran2 = new javax.swing.JComboBox<>();
        jB_Kembali = new javax.swing.JButton();
        jB_Beli2 = new javax.swing.JButton();
        jB_Ubah2 = new javax.swing.JButton();
        jB_Batal2 = new javax.swing.JButton();
        jB_Cetak2 = new javax.swing.JButton();
        jL_Background = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_Cetak2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 355));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(632, 355));
        jPanel1.setPreferredSize(new java.awt.Dimension(632, 355));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jT_Total2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 90, -1));

        jT_Jumlah2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_Jumlah2KeyReleased(evt);
            }
        });
        jPanel1.add(jT_Jumlah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 90, -1));

        jT_Harga2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_Harga2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jT_Harga2MouseReleased(evt);
            }
        });
        jT_Harga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Harga2ActionPerformed(evt);
            }
        });
        jPanel1.add(jT_Harga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 90, -1));

        jT_IDbarang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_IDbarang2ActionPerformed(evt);
            }
        });
        jPanel1.add(jT_IDbarang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 90, -1));

        jT_Ongkir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Ongkir2ActionPerformed(evt);
            }
        });
        jPanel1.add(jT_Ongkir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 90, -1));

        jL_JasaKirim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_JasaKirim.setText("Jasa Kirim");
        jPanel1.add(jL_JasaKirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 20));

        jL_IDbarang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_IDbarang.setText("ID Barang");
        jPanel1.add(jL_IDbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, 20));

        jL_Bayar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Bayar.setText("Pembayaran");
        jPanel1.add(jL_Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 20));

        jL_Ongkir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Ongkir.setText("Ongkir");
        jPanel1.add(jL_Ongkir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, 20));

        jL_Pesan.setFont(new java.awt.Font("Kartika", 1, 14)); // NOI18N
        jL_Pesan.setForeground(new java.awt.Color(255, 0, 0));
        jL_Pesan.setText("Hanya ShuttleCock Berkualitas yang Ada Di sini");
        jPanel1.add(jL_Pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jL_Total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Total.setText("Total Harga");
        jPanel1.add(jL_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, 40));

        jL_Harga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Harga.setText("Harga");
        jPanel1.add(jL_Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 40));

        jL_Merk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Merk.setForeground(new java.awt.Color(51, 51, 51));
        jL_Merk.setText("Merk");
        jPanel1.add(jL_Merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, 20));

        jL_Jumlah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Jumlah.setText("Jumlah Barang");
        jPanel1.add(jL_Jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, 20));

        jC_Merk2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "JPGold", "Glory", "Samurai", "Garuda", "Dakota" }));
        jC_Merk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_Merk2ActionPerformed(evt);
            }
        });
        jPanel1.add(jC_Merk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 90, 20));

        jC_JasaKirim2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "J&T Express", "JNE", "Tiki", "Wahana Express", "Ninja Express" }));
        jC_JasaKirim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_JasaKirim2ActionPerformed(evt);
            }
        });
        jPanel1.add(jC_JasaKirim2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jC_Pembayaran2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Transfer", "COD", "Indomaret", "OVO" }));
        jC_Pembayaran2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_Pembayaran2ActionPerformed(evt);
            }
        });
        jPanel1.add(jC_Pembayaran2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 90, -1));

        jB_Kembali.setText("Kembali");
        jB_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_KembaliActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jB_Beli2.setText("Beli");
        jB_Beli2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Beli2ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Beli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 70, -1));

        jB_Ubah2.setText("Ubah Pesanan");
        jB_Ubah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Ubah2ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Ubah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        jB_Batal2.setText("Batalkan Pesanan");
        jB_Batal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Batal2ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Batal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jB_Cetak2.setText("Cetak Struk");
        jB_Cetak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Cetak2ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Cetak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        jL_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Bg_ShuttleCock.jpg"))); // NOI18N
        jPanel1.add(jL_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 360);

        jTA_Cetak2.setColumns(20);
        jTA_Cetak2.setRows(5);
        jScrollPane1.setViewportView(jTA_Cetak2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(630, 0, 270, 360);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_KembaliActionPerformed
        GUI_MainMenu Me = new GUI_MainMenu();
        Me.setVisible(true);
        dispose();
    }//GEN-LAST:event_jB_KembaliActionPerformed

    private void jC_Merk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_Merk2ActionPerformed
          if (jC_Merk2.getSelectedItem().equals("JPGold")) {                                        //JIKA COMBO BOX YANG DIPILIH JPGold MAKA
            shuttle.setMerk("JPGold");                                                              //NILAI Variabel Merk JPGold
            shuttle.setHarga(75000);
        } else if (jC_Merk2.getSelectedItem().equals("Glory")) {                                    //JIKA COMBO BOX YANG DIPILIH Glory MAKA
            shuttle.setMerk("Glory");                                                               //NILAI Variabel Merk Glory
            shuttle.setHarga(57000);
        } else if (jC_Merk2.getSelectedItem().equals("Samurai")) {                                  //JIKA COMBO BOX YANG DIPILIH Samurai MAKA
            shuttle.setMerk("Samurai");                                                             //NILAI Variabel Merk Samurai
            shuttle.setHarga(90000);
        } else if (jC_Merk2.getSelectedItem().equals("Garuda")) {                                   //JIKA COMBO BOX YANG DIPILIH Garuda MAKA
            shuttle.setMerk("Garuda");                                                              //NILAI Variabel Merk Garuda
            shuttle.setHarga(105000);
        } else if (jC_Merk2.getSelectedItem().equals("Dakota")) {                                   //JIKA COMBO BOX YANG DIPILIH Dakota MAKA
            shuttle.setMerk("Dakota");                                                              //NILAI Variabel Merk Dakota
            shuttle.setHarga(45000);
        }
          jT_Harga2.setText("" + shuttle.getHarga()); 
    }//GEN-LAST:event_jC_Merk2ActionPerformed

    private void jT_Harga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Harga2ActionPerformed
       
    }//GEN-LAST:event_jT_Harga2ActionPerformed

    private void jT_Harga2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_Harga2MouseClicked
         
    }//GEN-LAST:event_jT_Harga2MouseClicked

    private void jT_Harga2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_Harga2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Harga2MouseReleased

    private void jT_Jumlah2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_Jumlah2KeyReleased
        int jml = Integer.parseInt(jT_Jumlah2.getText());                
        shuttle.setJumlah(jml);                                                                     //Menyimpan nilai pada textfield jumlah ke variabel jumlah
        shuttle.setTotalHarga(shuttle.getHarga(), shuttle.getJumlah(), shuttle.getOngkir());
        jT_Total2.setText("" + shuttle.getTotalHarga());
    }//GEN-LAST:event_jT_Jumlah2KeyReleased

    private void jB_Beli2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Beli2ActionPerformed
        shuttle.setIdBarang(jT_IDbarang2.getText());
        shuttle.insert();
    }//GEN-LAST:event_jB_Beli2ActionPerformed

    private void jB_Ubah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Ubah2ActionPerformed
        shuttle.setIdBarang(jT_IDbarang2.getText());
        shuttle.update();
    }//GEN-LAST:event_jB_Ubah2ActionPerformed

    private void jB_Batal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Batal2ActionPerformed
        shuttle.setIdBarang(jT_IDbarang2.getText());
        shuttle.delete();
    }//GEN-LAST:event_jB_Batal2ActionPerformed

    private void jB_Cetak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Cetak2ActionPerformed
        jTA_Cetak2.setText(shuttle.print());
     }//GEN-LAST:event_jB_Cetak2ActionPerformed

    private void jT_Ongkir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Ongkir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Ongkir2ActionPerformed

    private void jT_IDbarang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_IDbarang2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_IDbarang2ActionPerformed

    private void jC_JasaKirim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_JasaKirim2ActionPerformed
        if (jC_JasaKirim2.getSelectedItem().equals("J&T Express")) {
            shuttle.setJasaKirim("J&T Express");
            shuttle.setOngkir(19000);
        } else if (jC_JasaKirim2.getSelectedItem().equals("JNE")) {
            shuttle.setJasaKirim("JNE");
            shuttle.setOngkir(18000);
        } else if (jC_JasaKirim2.getSelectedItem().equals("Tiki")) {
            shuttle.setJasaKirim("Tiki");
            shuttle.setOngkir(15000);
        } else if (jC_JasaKirim2.getSelectedItem().equals("Wahana Express")) {
            shuttle.setJasaKirim("Wahana Express");
            shuttle.setOngkir(16000);
        } else if (jC_JasaKirim2.getSelectedItem().equals("Ninja Express")) {
            shuttle.setJasaKirim("Ninja Express");
            shuttle.setOngkir(12000);
        }

        jT_Ongkir2.setText("" + shuttle.getOngkir());
    }//GEN-LAST:event_jC_JasaKirim2ActionPerformed

    private void jC_Pembayaran2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_Pembayaran2ActionPerformed
        if (jC_Pembayaran2.getSelectedItem().equals("Transfer")) {
            shuttle.setPembayaran("Transfer");
            shuttle.setStatusPengiriman("Belum Dikirim");
        } else if (jC_Pembayaran2.getSelectedItem().equals("COD")) {
            shuttle.setPembayaran("COD");
            shuttle.setStatusPengiriman("Dikirim 2 Hari Lagi");
        } else if (jC_Pembayaran2.getSelectedItem().equals("Indomaret")) {
            shuttle.setPembayaran("Indomaret");
            shuttle.setStatusPengiriman("Belum Dikirim");
        } else if (jC_Pembayaran2.getSelectedItem().equals("OVO")) {
            shuttle.setPembayaran("OVO");
            shuttle.setStatusPengiriman("Belum Dikirim");
        }

    }//GEN-LAST:event_jC_Pembayaran2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Shuttlecock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Shuttlecock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Shuttlecock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Shuttlecock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Shuttlecock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Batal2;
    private javax.swing.JButton jB_Beli2;
    private javax.swing.JButton jB_Cetak2;
    private javax.swing.JButton jB_Kembali;
    private javax.swing.JButton jB_Ubah2;
    private javax.swing.JComboBox<String> jC_JasaKirim2;
    private javax.swing.JComboBox<String> jC_Merk2;
    private javax.swing.JComboBox<String> jC_Pembayaran2;
    private javax.swing.JLabel jL_Background;
    private javax.swing.JLabel jL_Bayar;
    private javax.swing.JLabel jL_Harga;
    private javax.swing.JLabel jL_IDbarang;
    private javax.swing.JLabel jL_JasaKirim;
    private javax.swing.JLabel jL_Jumlah;
    private javax.swing.JLabel jL_Merk;
    private javax.swing.JLabel jL_Ongkir;
    private javax.swing.JLabel jL_Pesan;
    private javax.swing.JLabel jL_Total;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTA_Cetak2;
    private javax.swing.JTextField jT_Harga2;
    private javax.swing.JTextField jT_IDbarang2;
    private javax.swing.JTextField jT_Jumlah2;
    private javax.swing.JTextField jT_Ongkir2;
    private javax.swing.JTextField jT_Total2;
    // End of variables declaration//GEN-END:variables
}
