package GUI;

import Objek.DataPembeli;
import javax.swing.JOptionPane;

/**
 *
 * @author Bima Hamdani Mawaridi
 */
public class GUI_MainMenu extends javax.swing.JFrame {

    DataPembeli data = new DataPembeli();                                           //Membuat objek class DataPembeli
    GUI_Shoes sepatu = new GUI_Shoes();
    GUI_Racket raket = new GUI_Racket();
    GUI_Shuttlecock cock = new GUI_Shuttlecock();
    GUI_Jersey jersey = new GUI_Jersey();

    /**
     * Creates new form MenuUtama
     */
    public GUI_MainMenu() {
        initComponents();

    }

    private void reset_form() {                                                     //MEMBUAT METHOD RESET UNTUK DIPANGGIL
        jT_Nama.setText("");                                                        //FUNGSI MENGKOSONGKAN FORM
        jT_NoTelp.setText("");
        jT_Tanggal.setText("");
        jC_Pulau.setSelectedItem("Pilih");
        jT_Alamat.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_background = new javax.swing.JPanel();
        jL_SelamatDatang = new javax.swing.JLabel();
        jL_isiData = new javax.swing.JLabel();
        jL_Nama = new javax.swing.JLabel();
        jL_Tanggal = new javax.swing.JLabel();
        jL_NoTelp = new javax.swing.JLabel();
        jL_Pulau = new javax.swing.JLabel();
        jL_Alamat = new javax.swing.JLabel();
        jL_Catatan = new javax.swing.JLabel();
        jL_Catatan1 = new javax.swing.JLabel();
        jT_Nama = new javax.swing.JTextField();
        jT_Tanggal = new javax.swing.JTextField();
        jT_NoTelp = new javax.swing.JTextField();
        jT_Alamat = new javax.swing.JTextField();
        jB_Simpan = new javax.swing.JButton();
        jB_Edit = new javax.swing.JButton();
        jB_Hapus = new javax.swing.JButton();
        jB_Raket = new javax.swing.JButton();
        jB_Cock = new javax.swing.JButton();
        jB_Jersey = new javax.swing.JButton();
        jB_Sepatu = new javax.swing.JButton();
        jB_Keluar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jC_Pulau = new javax.swing.JComboBox<>();
        jB_Cari = new javax.swing.JButton();
        jB_Confirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 550));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jP_background.setBackground(new java.awt.Color(204, 204, 255));
        jP_background.setMinimumSize(new java.awt.Dimension(680, 500));
        jP_background.setPreferredSize(new java.awt.Dimension(680, 500));
        jP_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_SelamatDatang.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jL_SelamatDatang.setForeground(new java.awt.Color(51, 0, 102));
        jL_SelamatDatang.setText("SELAMAT DATANG DI BIMA BADMINTON STORE");
        jP_background.add(jL_SelamatDatang, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, 578, 58));

        jL_isiData.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jL_isiData.setForeground(new java.awt.Color(51, 0, 0));
        jL_isiData.setText("Isi data di bawah ini terlebih dahulu  ");
        jP_background.add(jL_isiData, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 79, -1, 20));

        jL_Nama.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jL_Nama.setText("Nama");
        jP_background.add(jL_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, 40));

        jL_Tanggal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jL_Tanggal.setText("Tanggal");
        jP_background.add(jL_Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, 30));

        jL_NoTelp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jL_NoTelp.setText("No.Telp");
        jP_background.add(jL_NoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, 30));

        jL_Pulau.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jL_Pulau.setText("Pulau");
        jP_background.add(jL_Pulau, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, 30));

        jL_Alamat.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jL_Alamat.setText("Alamat");
        jP_background.add(jL_Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 40, 30));

        jL_Catatan.setForeground(java.awt.Color.red);
        jL_Catatan.setText("Nb: isikan nama kota/kabupaten dan provinsi");
        jP_background.add(jL_Catatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 270, 20));

        jL_Catatan1.setForeground(new java.awt.Color(102, 0, 102));
        jL_Catatan1.setText("Klik salah satu gambar untuk membeli barang yang anda cari");
        jP_background.add(jL_Catatan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 414, -1));

        jT_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NamaActionPerformed(evt);
            }
        });
        jP_background.add(jT_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 170, -1));

        jT_Tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_TanggalActionPerformed(evt);
            }
        });
        jP_background.add(jT_Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 170, -1));

        jT_NoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NoTelpActionPerformed(evt);
            }
        });
        jP_background.add(jT_NoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 170, -1));

        jT_Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_AlamatActionPerformed(evt);
            }
        });
        jP_background.add(jT_Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 170, -1));

        jB_Simpan.setText("Simpan");
        jB_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SimpanActionPerformed(evt);
            }
        });
        jP_background.add(jB_Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jB_Edit.setText("Edit");
        jB_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_EditActionPerformed(evt);
            }
        });
        jP_background.add(jB_Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 70, -1));

        jB_Hapus.setText("Hapus");
        jB_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_HapusActionPerformed(evt);
            }
        });
        jP_background.add(jB_Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jB_Raket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon_Raket.jpg"))); // NOI18N
        jB_Raket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_RaketActionPerformed(evt);
            }
        });
        jP_background.add(jB_Raket, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 71, 70));

        jB_Cock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon_Cock.jpg"))); // NOI18N
        jB_Cock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CockActionPerformed(evt);
            }
        });
        jP_background.add(jB_Cock, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 70, 70));

        jB_Jersey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon_Jersey.jpg"))); // NOI18N
        jB_Jersey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_JerseyActionPerformed(evt);
            }
        });
        jP_background.add(jB_Jersey, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 70, 70));

        jB_Sepatu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Icon_Sepatu.jpg"))); // NOI18N
        jB_Sepatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SepatuActionPerformed(evt);
            }
        });
        jP_background.add(jB_Sepatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 70, 70));

        jB_Keluar.setText("Keluar");
        jB_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_KeluarActionPerformed(evt);
            }
        });
        jP_background.add(jB_Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jP_background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 700, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jP_background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 340, 710, 10));

        jC_Pulau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Jawa / Bali", "Sumatera", "Kalimantan", "Sulawesi", "Papua / Maluku" }));
        jC_Pulau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_PulauActionPerformed(evt);
            }
        });
        jP_background.add(jC_Pulau, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 170, 30));

        jB_Cari.setText("Cari");
        jB_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CariActionPerformed(evt);
            }
        });
        jP_background.add(jB_Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 70, -1));

        jB_Confirm.setText("Konfirmasi Pembayaran");
        jB_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ConfirmActionPerformed(evt);
            }
        });
        jP_background.add(jB_Confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, -1, -1));

        getContentPane().add(jP_background);
        jP_background.setBounds(0, 0, 700, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jT_TanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_TanggalActionPerformed

    }//GEN-LAST:event_jT_TanggalActionPerformed

    private void jB_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SimpanActionPerformed
        data.setNama(jT_Nama.getText());
        data.setTanggal(jT_Tanggal.getText());
        data.setNoTelepon(jT_NoTelp.getText());
        data.setAlamat(jT_Alamat.getText());

        data.simpan();
    }//GEN-LAST:event_jB_SimpanActionPerformed

    private void jB_SepatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SepatuActionPerformed
     
        if (jT_Nama.getText().equals("") || jT_Tanggal.getText().equals("")                                     //KONDISI JIKA SALAH SATU TEXTFIELD KOSONG 
                || jC_Pulau.getSelectedItem().equals("Pilih") || jT_NoTelp.getText().equals("")) {

            JOptionPane.showMessageDialog                                                                       //JOPTION ERROR MESSAGE AKAN DITAMPILKAN, YANG
                    (this, "Mohon Isi Data Secara Lengkap",                                                     //BERISI MOHON ISI DATA
                            "Error", JOptionPane.ERROR_MESSAGE);
            sepatu.setVisible(false);                                                                           //TIDAK BISA MENAMPILKAN JFRAME SEPATU
        } else {
            sepatu.setVisible(true);                                                                            //AKAN BERALIH KE FORM PEMBELIAN RAKET
            dispose();                                                                                          //MENUTUP FORM MENU UTAMA
        }
    }//GEN-LAST:event_jB_SepatuActionPerformed

    private void jB_RaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_RaketActionPerformed
        
        if (jT_Nama.getText().equals("") || jT_Tanggal.getText().equals("") 
                || jC_Pulau.getSelectedItem().equals("Pilih") || jT_NoTelp.getText().equals("")) {

            JOptionPane.showMessageDialog 
                    (this, "Mohon Isi Data Secara Lengkap",                                                         
                            "Error", JOptionPane.ERROR_MESSAGE);
            raket.setVisible(false);                                                                               
        } else {
            raket.setVisible(true);                                                                                 
            dispose();                                                                                             
        }
    }//GEN-LAST:event_jB_RaketActionPerformed

    private void jB_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_KeluarActionPerformed
        int answer = JOptionPane.showConfirmDialog                                                                  //MENYIMPAN DATA OK OPTION KEDALAM VAR ANSWER
                (null, "Anda Yakin Keluar", "Keluar", JOptionPane.OK_OPTION);                                       //MENAMPILKAN JOPTIONPANE DAN MENANYAKAN APAKAH YAKIN UNTUK KELUAR?
        if (answer == JOptionPane.OK_OPTION) {                                                                      //JIKA USER MENEKAN OKE MAKA
            dispose();                                                                                              //TAMPILAN MENU UTAMA AKAN TERTUTUP
        }
    }//GEN-LAST:event_jB_KeluarActionPerformed

    private void jB_CockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CockActionPerformed
      
        if (jT_Nama.getText().equals("") || jT_Tanggal.getText().equals("")                                         
                || jC_Pulau.getSelectedItem().equals("Pilih") || jT_NoTelp.getText().equals("")) {

            JOptionPane.showMessageDialog                                                                           
                    (this, "Mohon Isi Data Secara Lengkap",                                                         
                            "Error", JOptionPane.ERROR_MESSAGE);
            cock.setVisible(false);                                                                                 
        } else {
            cock.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jB_CockActionPerformed

    private void jB_JerseyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_JerseyActionPerformed
         
        if (jT_Nama.getText().equals("") || jT_Tanggal.getText().equals("")                                         
                || jC_Pulau.getSelectedItem().equals("Pilih") || jT_NoTelp.getText().equals("")) {

            JOptionPane.showMessageDialog                                                                          
                    (this, "Mohon Isi Data Secara Lengkap",                                                         
                            "Error", JOptionPane.ERROR_MESSAGE);
            jersey.setVisible(false);                                                                              
        } else {
            jersey.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jB_JerseyActionPerformed

    private void jT_NoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NoTelpActionPerformed

    }//GEN-LAST:event_jT_NoTelpActionPerformed

    private void jT_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NamaActionPerformed

    }//GEN-LAST:event_jT_NamaActionPerformed

    private void jT_AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_AlamatActionPerformed

    private void jB_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_HapusActionPerformed
        data.hapus();
        reset_form();
    }//GEN-LAST:event_jB_HapusActionPerformed

    private void jB_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_EditActionPerformed
        data.setNama(jT_Nama.getText());
        data.setTanggal(jT_Tanggal.getText());
        data.setNoTelepon(jT_NoTelp.getText());
        data.setAlamat(jT_Alamat.getText());
        data.edit();
    }//GEN-LAST:event_jB_EditActionPerformed

    private void jC_PulauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_PulauActionPerformed
        if (jC_Pulau.getSelectedItem().equals("Jawa / Bali")) {
            data.setPulau("Jawa / Bali");
        } else if (jC_Pulau.getSelectedItem().equals("Sumatera")) {
            data.setPulau("Sumatera");
        } else if (jC_Pulau.getSelectedItem().equals("Kalimantan")) {
            data.setPulau("Kalimantan");
        } else if (jC_Pulau.getSelectedItem().equals("Sulawesi")) {
            data.setPulau("Sulawesi");
        } else if (jC_Pulau.getSelectedItem().equals("Papua / Maluku")) {
            data.setPulau("Papua / Maluku");
        }
    }//GEN-LAST:event_jC_PulauActionPerformed

    private void jB_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CariActionPerformed
        data.setNama(jT_Nama.getText());

        data.cari();
        jT_Nama.setText(data.getNama());
        jT_Tanggal.setText(data.getTanggal());
        jT_NoTelp.setText(data.getNoTelepon());
        jC_Pulau.setSelectedItem(data.getPulau());
        jT_Alamat.setText(data.getAlamat());
    }//GEN-LAST:event_jB_CariActionPerformed

    private void jB_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ConfirmActionPerformed
        GUI_Confirmation confirm = new GUI_Confirmation();
        confirm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jB_ConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Cari;
    private javax.swing.JButton jB_Cock;
    private javax.swing.JButton jB_Confirm;
    private javax.swing.JButton jB_Edit;
    private javax.swing.JButton jB_Hapus;
    private javax.swing.JButton jB_Jersey;
    private javax.swing.JButton jB_Keluar;
    private javax.swing.JButton jB_Raket;
    private javax.swing.JButton jB_Sepatu;
    private javax.swing.JButton jB_Simpan;
    private javax.swing.JComboBox<String> jC_Pulau;
    private javax.swing.JLabel jL_Alamat;
    private javax.swing.JLabel jL_Catatan;
    private javax.swing.JLabel jL_Catatan1;
    private javax.swing.JLabel jL_Nama;
    private javax.swing.JLabel jL_NoTelp;
    private javax.swing.JLabel jL_Pulau;
    private javax.swing.JLabel jL_SelamatDatang;
    private javax.swing.JLabel jL_Tanggal;
    private javax.swing.JLabel jL_isiData;
    private javax.swing.JPanel jP_background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jT_Alamat;
    private javax.swing.JTextField jT_Nama;
    private javax.swing.JTextField jT_NoTelp;
    private javax.swing.JTextField jT_Tanggal;
    // End of variables declaration//GEN-END:variables
}
