package GUI;

import Objek.*;

/**
 *
 * @author Bima Hamdani Mawaridi
 */
public class GUI_Jersey extends javax.swing.JFrame {
   
    Jersey baju = new Jersey();                                                         //membuat objek referensi dari class Jersey
   
    public GUI_Jersey() {
        initComponents();
        jT_Harga3.setEditable(false);
        jT_Ongkir3.setEditable(false);
        jT_Total3.setEditable(false);
        jTA_Cetak3.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jT_Harga3 = new javax.swing.JTextField();
        jT_NamaP3 = new javax.swing.JTextField();
        jT_Jumlah3 = new javax.swing.JTextField();
        jT_Total3 = new javax.swing.JTextField();
        jT_Ongkir3 = new javax.swing.JTextField();
        jT_IDBarang3 = new javax.swing.JTextField();
        jL_Merk = new javax.swing.JLabel();
        jL_Ukuran = new javax.swing.JLabel();
        jL_Harga = new javax.swing.JLabel();
        jL_NamaP = new javax.swing.JLabel();
        jL_Jumlah = new javax.swing.JLabel();
        jL_JasaKirim = new javax.swing.JLabel();
        jL_Total = new javax.swing.JLabel();
        jL_Ongkir = new javax.swing.JLabel();
        jL_IDBarang = new javax.swing.JLabel();
        jL_Pembayaran = new javax.swing.JLabel();
        jL_Pilih = new javax.swing.JLabel();
        jB_Kembali3 = new javax.swing.JButton();
        jB_Beli3 = new javax.swing.JButton();
        jB_Ubah3 = new javax.swing.JButton();
        jB_Batal3 = new javax.swing.JButton();
        jB_Cetak3 = new javax.swing.JButton();
        jC_Ukuran3 = new javax.swing.JComboBox<>();
        jC_Merk3 = new javax.swing.JComboBox<>();
        jC_Pembayaran3 = new javax.swing.JComboBox<>();
        jC_JasaKirim3 = new javax.swing.JComboBox<>();
        jL_Background = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_Cetak3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 355));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(600, 355));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 355));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jT_Harga3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 90, -1));

        jT_NamaP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_NamaP3ActionPerformed(evt);
            }
        });
        jPanel1.add(jT_NamaP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 90, -1));

        jT_Jumlah3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Jumlah3ActionPerformed(evt);
            }
        });
        jT_Jumlah3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_Jumlah3KeyReleased(evt);
            }
        });
        jPanel1.add(jT_Jumlah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 90, -1));

        jT_Total3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_Total3ActionPerformed(evt);
            }
        });
        jPanel1.add(jT_Total3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 90, -1));

        jT_Ongkir3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_Ongkir3KeyReleased(evt);
            }
        });
        jPanel1.add(jT_Ongkir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 90, -1));
        jPanel1.add(jT_IDBarang3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 90, -1));

        jL_Merk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Merk.setForeground(new java.awt.Color(204, 255, 255));
        jL_Merk.setText("Merk");
        jPanel1.add(jL_Merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 20));

        jL_Ukuran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Ukuran.setForeground(new java.awt.Color(204, 255, 255));
        jL_Ukuran.setText("Ukuran");
        jPanel1.add(jL_Ukuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        jL_Harga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Harga.setForeground(new java.awt.Color(204, 255, 255));
        jL_Harga.setText("Harga");
        jPanel1.add(jL_Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 40));

        jL_NamaP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jL_NamaP.setForeground(new java.awt.Color(204, 255, 255));
        jL_NamaP.setText("Nama Punggung");
        jPanel1.add(jL_NamaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jL_Jumlah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Jumlah.setForeground(new java.awt.Color(204, 255, 255));
        jL_Jumlah.setText("Jumlah Barang");
        jPanel1.add(jL_Jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, 20));

        jL_JasaKirim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_JasaKirim.setForeground(new java.awt.Color(204, 255, 255));
        jL_JasaKirim.setText("Jasa Kirim");
        jPanel1.add(jL_JasaKirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 20));

        jL_Total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Total.setForeground(new java.awt.Color(204, 255, 255));
        jL_Total.setText("Total Harga");
        jPanel1.add(jL_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, 20));

        jL_Ongkir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Ongkir.setForeground(new java.awt.Color(204, 255, 255));
        jL_Ongkir.setText("Ongkir");
        jPanel1.add(jL_Ongkir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, 20));

        jL_IDBarang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_IDBarang.setForeground(new java.awt.Color(204, 255, 255));
        jL_IDBarang.setText("ID Barang");
        jPanel1.add(jL_IDBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        jL_Pembayaran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Pembayaran.setForeground(new java.awt.Color(204, 255, 255));
        jL_Pembayaran.setText("Pembayaran");
        jPanel1.add(jL_Pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 20));

        jL_Pilih.setFont(new java.awt.Font("Kartika", 1, 16)); // NOI18N
        jL_Pilih.setForeground(new java.awt.Color(204, 255, 102));
        jL_Pilih.setText("Pilih Jersey Favorit Anda");
        jPanel1.add(jL_Pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jB_Kembali3.setText("Kembali");
        jB_Kembali3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Kembali3ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Kembali3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jB_Beli3.setText("Beli");
        jB_Beli3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Beli3ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Beli3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 80, -1));

        jB_Ubah3.setText("Ubah Pesanan");
        jB_Ubah3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Ubah3ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Ubah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jB_Batal3.setText("Batalkan Pesanan");
        jB_Batal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Batal3ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Batal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jB_Cetak3.setText("Cetak Struk");
        jB_Cetak3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Cetak3ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Cetak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        jC_Ukuran3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "M", "L", "XL", "XXL" }));
        jC_Ukuran3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_Ukuran3ActionPerformed(evt);
            }
        });
        jPanel1.add(jC_Ukuran3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 90, -1));

        jC_Merk3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Victor", "Li Ning", "Yonex" }));
        jC_Merk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_Merk3ActionPerformed(evt);
            }
        });
        jPanel1.add(jC_Merk3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 90, -1));

        jC_Pembayaran3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Transfer", "COD", "Indomaret", "OVO" }));
        jC_Pembayaran3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_Pembayaran3ActionPerformed(evt);
            }
        });
        jPanel1.add(jC_Pembayaran3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 90, -1));

        jC_JasaKirim3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "J&T Express", "JNE", "Tiki", "Wahana Express", "Ninja Express" }));
        jC_JasaKirim3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_JasaKirim3ActionPerformed(evt);
            }
        });
        jPanel1.add(jC_JasaKirim3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jL_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Bg_Jersey.jpg"))); // NOI18N
        jPanel1.add(jL_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTA_Cetak3.setColumns(20);
        jTA_Cetak3.setRows(5);
        jScrollPane1.setViewportView(jTA_Cetak3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 300, 360));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 355);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_Kembali3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Kembali3ActionPerformed
        GUI_MainMenu Men = new GUI_MainMenu();
        Men.setVisible(true);
        dispose();
    }//GEN-LAST:event_jB_Kembali3ActionPerformed

    private void jT_NamaP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_NamaP3ActionPerformed
       
    }//GEN-LAST:event_jT_NamaP3ActionPerformed

    private void jC_Merk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_Merk3ActionPerformed
        if (jC_Merk3.getSelectedItem().equals("Victor")) {                                
            baju.setMerk("Victor");                                                              
            baju.setHarga(273000);
        } else if (jC_Merk3.getSelectedItem().equals("Li Ning")) {                                      
            baju.setMerk("Li Ning");                                                             
            baju.setHarga(189000);
        } else if (jC_Merk3.getSelectedItem().equals("Yonex")) {                                 
            baju.setMerk("Yonex");                                                            
            baju.setHarga(200000);
        }
    }//GEN-LAST:event_jC_Merk3ActionPerformed

    private void jC_Ukuran3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_Ukuran3ActionPerformed
        int harga = 0;
        if (jC_Ukuran3.getSelectedItem().equals("M")) {                                      
            baju.setUkuran("M");
            baju.setHargaUkuran(0);
            harga = baju.getHarga() + baju.getHargaUkuran();
        } else if (jC_Ukuran3.getSelectedItem().equals("L")) {                                     
            baju.setUkuran("L");
            baju.setHargaUkuran(10000);
            harga = baju.getHarga() + baju.getHargaUkuran();
        }else if (jC_Ukuran3.getSelectedItem().equals("XL")) {                                     
            baju.setUkuran("XL");
            baju.setHargaUkuran(20000);
            harga = baju.getHarga() + baju.getHargaUkuran();
        }else if (jC_Ukuran3.getSelectedItem().equals("XXL")) {                                      
            baju.setUkuran("XXL");
            baju.setHargaUkuran(40000);
            harga = baju.getHarga() + baju.getHargaUkuran();
        }
        jT_Harga3.setText("" + harga);          
    }//GEN-LAST:event_jC_Ukuran3ActionPerformed

    private void jT_Jumlah3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Jumlah3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Jumlah3ActionPerformed

    private void jT_Jumlah3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_Jumlah3KeyReleased
        int jml = Integer.parseInt(jT_Jumlah3.getText());                
        baju.setJumlah(jml);                                                                            //Menyimpan nilai pada textfield jumlah ke variabel jumlah
        baju.setTotalHarga(baju.getHarga(), baju.getHargaUkuran(), baju.getJumlah(), baju.getOngkir());
        jT_Total3.setText("" + baju.getTotalHarga());
    }//GEN-LAST:event_jT_Jumlah3KeyReleased

    private void jT_Ongkir3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_Ongkir3KeyReleased
 
    }//GEN-LAST:event_jT_Ongkir3KeyReleased

    private void jB_Beli3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Beli3ActionPerformed
        baju.setNamaPunggung(jT_NamaP3.getText());
        baju.setIdBarang(jT_IDBarang3.getText());
        baju.insert();
    }//GEN-LAST:event_jB_Beli3ActionPerformed

    private void jB_Batal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Batal3ActionPerformed
        baju.setIdBarang(jT_IDBarang3.getText());
        baju.delete();
    }//GEN-LAST:event_jB_Batal3ActionPerformed

    private void jT_Total3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_Total3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_Total3ActionPerformed

    private void jB_Ubah3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Ubah3ActionPerformed
        baju.setNamaPunggung(jT_NamaP3.getText());
        baju.setIdBarang(jT_IDBarang3.getText());
        baju.update();
    }//GEN-LAST:event_jB_Ubah3ActionPerformed

    private void jB_Cetak3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Cetak3ActionPerformed
         jTA_Cetak3.setText(baju.print());
               
    }//GEN-LAST:event_jB_Cetak3ActionPerformed

    private void jC_JasaKirim3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_JasaKirim3ActionPerformed
        if (jC_JasaKirim3.getSelectedItem().equals("J&T Express")) {
            baju.setJasaKirim("J&T Express");
            baju.setOngkir(19000);
        } else if (jC_JasaKirim3.getSelectedItem().equals("JNE")) {
            baju.setJasaKirim("JNE");
            baju.setOngkir(18000);
        } else if (jC_JasaKirim3.getSelectedItem().equals("Tiki")) {
            baju.setJasaKirim("Tiki");
            baju.setOngkir(15000);
        } else if (jC_JasaKirim3.getSelectedItem().equals("Wahana Express")) {
            baju.setJasaKirim("Wahana Express");
            baju.setOngkir(16000);
        } else if (jC_JasaKirim3.getSelectedItem().equals("Ninja Express")) {
            baju.setJasaKirim("Ninja Express");
            baju.setOngkir(12000);
        }

        jT_Ongkir3.setText("" + baju.getOngkir());
    }//GEN-LAST:event_jC_JasaKirim3ActionPerformed

    private void jC_Pembayaran3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_Pembayaran3ActionPerformed
        if (jC_Pembayaran3.getSelectedItem().equals("Transfer")) {
            baju.setPembayaran("Transfer");
            baju.setStatusPengiriman("Belum Dikirim");
        } else if (jC_Pembayaran3.getSelectedItem().equals("COD")) {
            baju.setPembayaran("COD");
            baju.setStatusPengiriman("Dikirim 2 Hari Lagi");
        } else if (jC_Pembayaran3.getSelectedItem().equals("Indomaret")) {
            baju.setPembayaran("Indomaret");
            baju.setStatusPengiriman("Belum Dikirim");
        } else if (jC_Pembayaran3.getSelectedItem().equals("OVO")) {
            baju.setPembayaran("OVO");
            baju.setStatusPengiriman("Belum Dikirim");
        }

    }//GEN-LAST:event_jC_Pembayaran3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Jersey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Jersey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Jersey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Jersey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Jersey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Batal3;
    private javax.swing.JButton jB_Beli3;
    private javax.swing.JButton jB_Cetak3;
    private javax.swing.JButton jB_Kembali3;
    private javax.swing.JButton jB_Ubah3;
    private javax.swing.JComboBox<String> jC_JasaKirim3;
    private javax.swing.JComboBox<String> jC_Merk3;
    private javax.swing.JComboBox<String> jC_Pembayaran3;
    private javax.swing.JComboBox<String> jC_Ukuran3;
    private javax.swing.JLabel jL_Background;
    private javax.swing.JLabel jL_Harga;
    private javax.swing.JLabel jL_IDBarang;
    private javax.swing.JLabel jL_JasaKirim;
    private javax.swing.JLabel jL_Jumlah;
    private javax.swing.JLabel jL_Merk;
    private javax.swing.JLabel jL_NamaP;
    private javax.swing.JLabel jL_Ongkir;
    private javax.swing.JLabel jL_Pembayaran;
    private javax.swing.JLabel jL_Pilih;
    private javax.swing.JLabel jL_Total;
    private javax.swing.JLabel jL_Ukuran;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTA_Cetak3;
    private javax.swing.JTextField jT_Harga3;
    private javax.swing.JTextField jT_IDBarang3;
    private javax.swing.JTextField jT_Jumlah3;
    private javax.swing.JTextField jT_NamaP3;
    private javax.swing.JTextField jT_Ongkir3;
    private javax.swing.JTextField jT_Total3;
    // End of variables declaration//GEN-END:variables
}
