package GUI;

import Objek.Sepatu ;
       
         /**
         *
         * @author Bima Hamdani Mawaridi
         */

public class GUI_Shoes extends javax.swing.JFrame {

    Sepatu shoes = new Sepatu();

    public GUI_Shoes() {
        initComponents();
        jT_Harga4.setEditable(false);
        jT_Total4.setEditable(false);
        jT_Ongkir4.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jL_Merk = new javax.swing.JLabel();
        jL_Nomor = new javax.swing.JLabel();
        jL_Harga = new javax.swing.JLabel();
        jL_Warna = new javax.swing.JLabel();
        jL_Jumlah = new javax.swing.JLabel();
        jL_Total = new javax.swing.JLabel();
        jL_Bayar = new javax.swing.JLabel();
        jL_Silahkan = new javax.swing.JLabel();
        jL_JasaKirim = new javax.swing.JLabel();
        jL_Ongkir = new javax.swing.JLabel();
        jL_IDbarang3 = new javax.swing.JLabel();
        jT_Harga4 = new javax.swing.JTextField();
        jT_Jumlah4 = new javax.swing.JTextField();
        jT_Total4 = new javax.swing.JTextField();
        jT_IDbarang4 = new javax.swing.JTextField();
        jT_Ongkir4 = new javax.swing.JTextField();
        jC_Warna = new javax.swing.JComboBox<>();
        jC_Merk4 = new javax.swing.JComboBox<>();
        jC_Nomor4 = new javax.swing.JComboBox<>();
        jC_Pembayaran4 = new javax.swing.JComboBox<>();
        jC_JasaKirim4 = new javax.swing.JComboBox<>();
        jB_Kembali4 = new javax.swing.JButton();
        jB_Beli4 = new javax.swing.JButton();
        jB_Ubah4 = new javax.swing.JButton();
        jB_Batal4 = new javax.swing.JButton();
        jB_Cetak4 = new javax.swing.JButton();
        jL_Background = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_Cetak4 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 355));
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(565, 355));
        jPanel1.setPreferredSize(new java.awt.Dimension(565, 355));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_Merk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Merk.setText("Merk");
        jPanel1.add(jL_Merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 20));

        jL_Nomor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Nomor.setText("Nomor");
        jPanel1.add(jL_Nomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 20));

        jL_Harga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Harga.setText("Harga");
        jPanel1.add(jL_Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 40));

        jL_Warna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Warna.setText("Warna");
        jPanel1.add(jL_Warna, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        jL_Jumlah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Jumlah.setText("Jumlah Barang");
        jPanel1.add(jL_Jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, 20));

        jL_Total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Total.setText("Total Harga");
        jPanel1.add(jL_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, 20));

        jL_Bayar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Bayar.setText("Pembayaran");
        jPanel1.add(jL_Bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jL_Silahkan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jL_Silahkan.setForeground(new java.awt.Color(153, 0, 0));
        jL_Silahkan.setText("Silahkan Pilih Sepatu Yang Pas Untuk Anda");
        jPanel1.add(jL_Silahkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 310, -1));

        jL_JasaKirim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_JasaKirim.setText("Jasa Kirim");
        jPanel1.add(jL_JasaKirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, 20));

        jL_Ongkir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_Ongkir.setText("Ongkir");
        jPanel1.add(jL_Ongkir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        jL_IDbarang3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jL_IDbarang3.setText("ID Barang");
        jPanel1.add(jL_IDbarang3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, 20));
        jPanel1.add(jT_Harga4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, -1));

        jT_Jumlah4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_Jumlah4KeyReleased(evt);
            }
        });
        jPanel1.add(jT_Jumlah4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 90, -1));
        jPanel1.add(jT_Total4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 90, -1));
        jPanel1.add(jT_IDbarang4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 90, -1));
        jPanel1.add(jT_Ongkir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 90, -1));

        jC_Warna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Merah", "Kuning", "Biru", "Orange" }));
        jC_Warna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_WarnaActionPerformed(evt);
            }
        });
        jPanel1.add(jC_Warna, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 90, -1));

        jC_Merk4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Asics", "Eagle", "ReinforceSpeed", "Yonex", "Victor", "Li Ning" }));
        jC_Merk4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_Merk4ActionPerformed(evt);
            }
        });
        jPanel1.add(jC_Merk4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jC_Nomor4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "39", "40", "41", "42", "43" }));
        jC_Nomor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_Nomor4ActionPerformed(evt);
            }
        });
        jPanel1.add(jC_Nomor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jC_Pembayaran4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Transfer", "COD", "Indomaret", "OVO" }));
        jC_Pembayaran4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_Pembayaran4ActionPerformed(evt);
            }
        });
        jPanel1.add(jC_Pembayaran4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 90, -1));

        jC_JasaKirim4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "J&T Express", "JNE", "Tiki", "Wahana Express", "Ninja Express" }));
        jC_JasaKirim4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_JasaKirim4ActionPerformed(evt);
            }
        });
        jPanel1.add(jC_JasaKirim4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        jB_Kembali4.setText("Kembali");
        jB_Kembali4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Kembali4ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Kembali4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jB_Beli4.setText("Beli");
        jB_Beli4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Beli4ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Beli4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 80, -1));

        jB_Ubah4.setText("Ubah Pesanan");
        jB_Ubah4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Ubah4ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Ubah4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        jB_Batal4.setText("Batalkan Pesanan");
        jB_Batal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Batal4ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Batal4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jB_Cetak4.setText("Cetak Struk");
        jB_Cetak4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Cetak4ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_Cetak4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        jL_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Bg_Sepatu.jpg"))); // NOI18N
        jPanel1.add(jL_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 565, 360);

        jTA_Cetak4.setColumns(20);
        jTA_Cetak4.setRows(5);
        jScrollPane1.setViewportView(jTA_Cetak4);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(560, 0, 340, 360);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_Kembali4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Kembali4ActionPerformed
        GUI_MainMenu Menu = new GUI_MainMenu();
        Menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jB_Kembali4ActionPerformed

    private void jC_Merk4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_Merk4ActionPerformed
        if (jC_Merk4.getSelectedItem().equals("Asics")) {                                      
            shoes.setMerk("Asics");                                                             
            shoes.setHarga(1450000);
        } else if (jC_Merk4.getSelectedItem().equals("Eagle")) {                                
            shoes.setMerk("Eagle");                                                             
            shoes.setHarga(284000);
        } else if (jC_Merk4.getSelectedItem().equals("ReinforceSpeed")) {                                 
            shoes.setMerk("ReinforceSpeed");                                                                
            shoes.setHarga(345000);
        } else if (jC_Merk4.getSelectedItem().equals("Yonex")) {                                 
            shoes.setMerk("Yonex");                                                               
            shoes.setHarga(1935000);
        } else if (jC_Merk4.getSelectedItem().equals("Victor")) {                                
            shoes.setMerk("Victor");                                                               
            shoes.setHarga(1430000);
        } else if (jC_Merk4.getSelectedItem().equals("Li Ning")) {                                
            shoes.setMerk("Li Ning");                                                              
            shoes.setHarga(1552000);
        }
        

    }//GEN-LAST:event_jC_Merk4ActionPerformed

    private void jC_Nomor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_Nomor4ActionPerformed
        int harga = 0;
        if (jC_Nomor4.getSelectedItem().equals("39")) {                                      
            shoes.setNomor("39");
            shoes.setHarganomor(0);
            harga = shoes.getHarga() + shoes.getHarganomor();
        } else if (jC_Nomor4.getSelectedItem().equals("40")) {                               
            shoes.setNomor("40");
            shoes.setHarganomor(5000);
            harga = shoes.getHarga() + shoes.getHarganomor();
        } else if (jC_Nomor4.getSelectedItem().equals("41")) {                                
            shoes.setNomor("41");
            shoes.setHarganomor(10000);
            harga = shoes.getHarga() + shoes.getHarganomor();
        } else if (jC_Nomor4.getSelectedItem().equals("42")) {                              
            shoes.setNomor("42");
            shoes.setHarganomor(15000);
            harga = shoes.getHarga() + shoes.getHarganomor();
        } else if (jC_Nomor4.getSelectedItem().equals("43")) {                                
            shoes.setNomor("43");
            shoes.setHarganomor(20000);
            harga = shoes.getHarga() + shoes.getHarganomor();
        } 
  
        jT_Harga4.setText("" + harga); 
      
    }//GEN-LAST:event_jC_Nomor4ActionPerformed

    private void jT_Jumlah4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_Jumlah4KeyReleased
        int jml = Integer.parseInt(jT_Jumlah4.getText());                
        shoes.setJumlah(jml);                                                                                   //Menyimpan nilai pada textfield jumlah ke variabel jumlah
        shoes.setTotalHarga(shoes.getHarga(), shoes.getHarganomor(), shoes.getJumlah(), shoes.getOngkir());
        jT_Total4.setText("" + shoes.getTotalHarga());        
    }//GEN-LAST:event_jT_Jumlah4KeyReleased

    private void jB_Beli4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Beli4ActionPerformed
        shoes.setIdBarang(jT_IDbarang4.getText());
        shoes.insert();
    }//GEN-LAST:event_jB_Beli4ActionPerformed

    private void jB_Ubah4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Ubah4ActionPerformed
        shoes.setIdBarang(jT_IDbarang4.getText());
        shoes.update();
    }//GEN-LAST:event_jB_Ubah4ActionPerformed

    private void jB_Batal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Batal4ActionPerformed
        shoes.setIdBarang(jT_IDbarang4.getText());
        shoes.delete();
    }//GEN-LAST:event_jB_Batal4ActionPerformed

    private void jB_Cetak4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Cetak4ActionPerformed
        jTA_Cetak4.setText(shoes.print());

    }//GEN-LAST:event_jB_Cetak4ActionPerformed

    private void jC_Pembayaran4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_Pembayaran4ActionPerformed
       if (jC_Pembayaran4.getSelectedItem().equals("Transfer")) {
            shoes.setPembayaran("Transfer");
            shoes.setStatusPengiriman("Belum Dikirim");
        } else if (jC_Pembayaran4.getSelectedItem().equals("COD")) {
            shoes.setPembayaran("COD");
            shoes.setStatusPengiriman("Dikirim 2 Hari Lagi");
        } else if (jC_Pembayaran4.getSelectedItem().equals("Indomaret")) {
            shoes.setPembayaran("Indomaret");
            shoes.setStatusPengiriman("Belum Dikirim");
        } else if (jC_Pembayaran4.getSelectedItem().equals("OVO")) {
            shoes.setPembayaran("OVO");
            shoes.setStatusPengiriman("Belum Dikirim");
        }
    }//GEN-LAST:event_jC_Pembayaran4ActionPerformed

    private void jC_WarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_WarnaActionPerformed
       if (jC_Warna.getSelectedItem().equals("Merah")) {
            shoes.setWarna("Merah");
        } else if (jC_Warna.getSelectedItem().equals("Kuning")) {
            shoes.setWarna("Kuning");
        } else if (jC_Warna.getSelectedItem().equals("Biru")) {
            shoes.setWarna("Biru");
        } else if (jC_Warna.getSelectedItem().equals("Orange")) {
            shoes.setWarna("Orange");
        }
    }//GEN-LAST:event_jC_WarnaActionPerformed

    private void jC_JasaKirim4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_JasaKirim4ActionPerformed
        if (jC_JasaKirim4.getSelectedItem().equals("J&T Express")) {
            shoes.setJasaKirim("J&T Express");
            shoes.setOngkir(19000);
        } else if (jC_JasaKirim4.getSelectedItem().equals("JNE")) {
            shoes.setJasaKirim("JNE");
            shoes.setOngkir(18000);
        } else if (jC_JasaKirim4.getSelectedItem().equals("Tiki")) {
            shoes.setJasaKirim("Tiki");
            shoes.setOngkir(15000);
        } else if (jC_JasaKirim4.getSelectedItem().equals("Wahana Express")) {
            shoes.setJasaKirim("Wahana Express");
            shoes.setOngkir(16000);
        } else if (jC_JasaKirim4.getSelectedItem().equals("Ninja Express")) {
            shoes.setJasaKirim("Ninja Express");
            shoes.setOngkir(12000);
        }

        jT_Ongkir4.setText("" + shoes.getOngkir());
    }//GEN-LAST:event_jC_JasaKirim4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Shoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Shoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Shoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Shoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Shoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Batal4;
    private javax.swing.JButton jB_Beli4;
    private javax.swing.JButton jB_Cetak4;
    private javax.swing.JButton jB_Kembali4;
    private javax.swing.JButton jB_Ubah4;
    private javax.swing.JComboBox<String> jC_JasaKirim4;
    private javax.swing.JComboBox<String> jC_Merk4;
    private javax.swing.JComboBox<String> jC_Nomor4;
    private javax.swing.JComboBox<String> jC_Pembayaran4;
    private javax.swing.JComboBox<String> jC_Warna;
    private javax.swing.JLabel jL_Background;
    private javax.swing.JLabel jL_Bayar;
    private javax.swing.JLabel jL_Harga;
    private javax.swing.JLabel jL_IDbarang3;
    private javax.swing.JLabel jL_JasaKirim;
    private javax.swing.JLabel jL_Jumlah;
    private javax.swing.JLabel jL_Merk;
    private javax.swing.JLabel jL_Nomor;
    private javax.swing.JLabel jL_Ongkir;
    private javax.swing.JLabel jL_Silahkan;
    private javax.swing.JLabel jL_Total;
    private javax.swing.JLabel jL_Warna;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTA_Cetak4;
    private javax.swing.JTextField jT_Harga4;
    private javax.swing.JTextField jT_IDbarang4;
    private javax.swing.JTextField jT_Jumlah4;
    private javax.swing.JTextField jT_Ongkir4;
    private javax.swing.JTextField jT_Total4;
    // End of variables declaration//GEN-END:variables
}
