package GUI;

/**
 *
 * @author Bima Hamdani Mawaridi
 */
public class GUI_Loading extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public GUI_Loading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1_Background = new javax.swing.JPanel();
        jLabel1_Foto = new javax.swing.JLabel();
        jLabel1_Loading = new javax.swing.JLabel();
        jLabel1_Persen = new javax.swing.JLabel();
        LoadingBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1_Background.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1_Background.setPreferredSize(new java.awt.Dimension(686, 460));

        jLabel1_Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BG_Loading.jpg"))); // NOI18N

        jLabel1_Loading.setText("Loading....");

        jLabel1_Persen.setText("0 %");

        javax.swing.GroupLayout jPanel1_BackgroundLayout = new javax.swing.GroupLayout(jPanel1_Background);
        jPanel1_Background.setLayout(jPanel1_BackgroundLayout);
        jPanel1_BackgroundLayout.setHorizontalGroup(
            jPanel1_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1_BackgroundLayout.createSequentialGroup()
                .addComponent(jLabel1_Loading)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_BackgroundLayout.createSequentialGroup()
                .addComponent(LoadingBar, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1_Persen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1_BackgroundLayout.setVerticalGroup(
            jPanel1_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_BackgroundLayout.createSequentialGroup()
                .addComponent(jLabel1_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1_Persen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LoadingBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel1_Loading)
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        GUI_Loading loading = new GUI_Loading();
        loading.setVisible(true);

        try {

            for (int i = 0; i <= 100; i++) {
                Thread.sleep(60);                                                     //mengatur berapa lama loading bar berjalan
                loading.jLabel1_Persen.setText(i + "%");

                if (i == 50) {
                    loading.jLabel1_Loading.setText("Connection to database...");
                }
                if (i == 80) {
                    loading.jLabel1_Loading.setText("Launching Application...");
                }
                loading.LoadingBar.setValue(i);
            }

            new GUI_MainMenu().setVisible(true);                                     //Menampilkan FormMenuUtama
            loading.dispose();                                                       //Menutup FormLoading

        } catch (InterruptedException e) {

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel jLabel1_Foto;
    private javax.swing.JLabel jLabel1_Loading;
    private javax.swing.JLabel jLabel1_Persen;
    private javax.swing.JPanel jPanel1_Background;
    // End of variables declaration//GEN-END:variables
}
